from os import system
print("请确保您的Mac已连接Interrnet……\nCopyright © 俊熹之星 & 任俊熹的团队 , 保留一切权利.")
print("配置Python")
system(" /Applications/Python\ 3.8/Install\ Certificates.command ")
print("安装(Pygame的依赖包)的依赖包brew")
system("/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"")
print("安装Pygame的依赖包 sdl smpeg sdl_image sdl_mixer sdl_ttf portmidi hg sdl_mixer portmidi")
system("brew install sdl smpeg sdl_image sdl_mixer sdl_ttf portmidi hg sdl_mixer portmidi")
print("验证安装")
system("brew install sdl smpeg sdl_image sdl_mixer sdl_ttf portmidi hg sdl_mixer portmidi")
print("验证安装")
system("brew install sdl smpeg sdl_image sdl_mixer sdl_ttf portmidi hg sdl_mixer portmidi")
print("验证安装")
system("brew install sdl smpeg sdl_image sdl_mixer sdl_ttf portmidi hg sdl_mixer portmidi")
print("验证安装")
system("brew install sdl smpeg sdl_image sdl_mixer sdl_ttf portmidi hg sdl_mixer portmidi")
print("验证安装")
system("brew install sdl smpeg sdl_image sdl_mixer sdl_ttf portmidi hg sdl_mixer portmidi")
print("依赖包安装完成,开始安装Pygame.")
system("pip3 install pygame -i https:\\pypi.doubanio.com\simple")
print("完成!")
print("验证安装Pygame")
system(" /Applications/Python\ 3.8/Install\ Certificates.command ")
system("python -m pygame")
print("复原更改的设置")
system(" /Applications/Python\ 3.8/Install\ Certificates.command ")
print("完成!")
